spring.application.name=sportcity-api

# Puerto dinámico para Render
server.port=${PORT:8080}

# Configuracion Base de Datos H2
spring.datasource.url=jdbc:h2:file:./data/sportcitydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracion JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect