spring.application.name=sportcity-api

# Puerto para Render
server.port=${PORT:8080}

# Configuración BD
spring.datasource.url=jdbc:h2:file:./data/sportcitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Para ver en la consola lo que pasa
spring.jpa.show-sql=true